### Get all persons
GET http://localhost:3001/api/persons

### Delete single person
DELETE http://localhost:3001/api/persons/5f5d9cbd8111e9063c139749

### Add a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "a",
    "number": "123"
}

### get a specific person. 5f5d7e52a082ad051c56e6cc
GET http://localhost:3001/api/persons/5f5d9d3a6a205d1338f4c779

### get info
GET http://localhost:3001/info

### PUT
PUT http://localhost:3001/api/persons/5f5d9d3a6a205d1338f4c779
Content-Type: application/json

{
    "name": "Mikhail",
    "number": "1234566789"
}