### Get all persons
GET http://localhost:3001/api/persons

### Delete single person
DELETE http://localhost:3001/api/persons/5

### Add a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mikhail",
    "number": "1234567"
}

### get a specific person. 5f5d7e52a082ad051c56e6cc
GET http://localhost:3001/api/persons/5f5d7e52a082ad051c56e6cc

### get info
GET http://localhost:3001/info
